version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /express-mongodb/src
      - /npm
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directories:
      - /express-mongodb
    schedule:
      interval: monthly
