services:
  app:
    build:
      context: .
      args:
        NODE_IMAGE:
    image: $APP_IMAGE
    depends_on:
      - db
    environment:
      DATABASE_URL:
  db:
    image: $MONGODB_IMAGE
    volumes:
      - db:/data/db
    environment:
      MONGO_INITDB_DATABASE: todo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
volumes:
  db:
