service: serverless

frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-offline-direct-lambda
  - serverless-offline

# custom:
#   webpack:
#     webpackConfig: ./webpack.config.js
#   serverless-offline:
#     host: 0.0.0.0
#     httpPort: 3000

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: handler.hello
    events:
      # - httpApi:
      - http:
          path: /users/create
          method: get
