name: Check Secret

on:
  push:
    branches:
      - prod

jobs:
  show:
    runs-on: ubuntu-latest

    steps:
      - name: Set DUMMY
        run: |
          echo "Secret value: dummy"
          echo "DUMMY=dummy" >> $GITHUB_ENV
      - name: Set BAR from FOO
        run: |
          echo "Secret value: ${{ env.FOO }}"
          echo "BAR=${{ env.FOO }}" >> $GITHUB_ENV
      - name: Set NPM_TOKEN
        run: |
          echo "Secret value: ${{ secrets.NPM_TOKEN }}"
          echo "NPM_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV
      - name: Set GITHUB_TOKEN
        run: |
          echo "Secret value: ${{ secrets.GITHUB_TOKEN }}"
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: Print Secret Values
        run: |
          echo "DUMMY: ${{ env.DUMMY }}"
          echo "FOO: ${{ env.FOO }}"
          echo "BAR: ${{ env.BAR }}"
          echo "NPM_TOKEN: ${{ env.NPM_TOKEN }}"
          echo "GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}"
          echo "DUMMY: ${{ env.DUMMY }}" | wc -m
          echo "FOO: ${{ env.FOO }}" | wc -m
          echo "BAR: ${{ env.BAR }}" | wc -m
          echo "NPM_TOKEN: ${{ env.NPM_TOKEN }}" | wc -m
          echo "GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}" | wc -m
